coffee_map:
  '00000001': 0
  '00000002': 3
  '00000003': 4
  '00000004': 1
  '00000005': 5
  '00000006': 2
db_charset: utf8
db_host: 192.168.10.22
db_login_timeout: 5
db_name: KIOSK
db_pwd: NEUROMEKA1234
db_timeout: 5
db_user: NEUROMEKA
espresso_machine_long_delay_1: 12
espresso_machine_long_delay_2: 12
espresso_machine_shot_delay_1: 6
espresso_machine_shot_delay_2: 6
coffee_expiry_time: 600
robot_dof: 6
water_only: 0
ice_only: 4
ice_and_water: 1
milk_refresh_duration: 4800
cup_disp_packet_len: 11
ice_disp_packet_len: 5
lift_delay: 10
lift_cup_delay: 1
