#!/bin/bash

### BEGIN INIT INFO
# Provides: Neuromeka-STEP-PC
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Sample script description
### END INIT INFO

ServiceName=coffee_automation_service

status() {
    ps -ef | grep "/bin/bash /etc/$ServiceName\_main_script"
    tail -f /tmp/$ServiceName.log
}

start() {
    echo "Started $ServiceName\_main_script service"
	/usr/bin/screen -dmS $ServiceName bash -c "sudo /etc/$ServiceName\_main_script > /tmp/$ServiceName.log 2>&1"
	echo -e \n
}

stop() {
    ps -ef | grep "/bin/bash /etc/$ServiceName\_main_script" | awk '{print $2}' | sudo xargs kill -9
    echo "Stopped $ServiceName\_main_script service"
    echo -e '\n'
}

case $1 in
    start)
        start;;
    stop)
        stop;;
    restart)
        stop
        start;;
    status)
        status;;
esac
exit 0
